name: Deploy Backend Stack

on:
    workflow_dispatch:
      inputs:
        stage:
          description: 'Environment stage'
          required: true
          default: 'prod'
        appname:
          description: 'Application name'
          required: true
          default: 'greetings'

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    permissions:
        id-token: write
        contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Assume Role with OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
         role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/${{ github.event.inputs.appname }}-${{ vars.CDK_ROLE_NAME }}-${{ github.event.inputs.stage }}
         role-session-name: GitHubActions
         aws-region: ${{ vars.AWS_REGION }}

      - name: Build backend
        run: cd ${{ vars.BACKEND_DIR }} && npm ci && npm run build && npm run zip

      - name: (for Dev) Upload to S3 
        if: ${{ github.event.inputs.stage == 'dev' }}
        run: |
          aws s3 cp ${{ vars.BACKEND_DIR }}/lambda-backend.zip s3://${{ github.event.inputs.appname }}-lambda-code-repo-dev/${{ github.event.inputs.appname }}/dev/lambda-backend.zip

      - name: (For Dev) Update Lambda Code
        if: ${{ github.event.inputs.stage == 'dev' }}
        run: |
          aws lambda update-function-code \
            --function-name greetings-GreetingFunction-dev \
            --s3-bucket ${{ github.event.inputs.appname }}-lambda-code-repo-dev \
            --s3-key ${{ github.event.inputs.appname }}/dev/lambda-backend.zip \
            --publish

      - name: (For Prod) Upload and get S3 versionId
        if: ${{ github.event.inputs.stage != 'dev' }}
        id: upload
        run: |
          OUTPUT=$(aws s3api put-object \
            --bucket "${{ github.event.inputs.appname }}-lambda-code-repo-${{ github.event.inputs.stage }}" \
            --key "${{ github.event.inputs.appname }}/${{ github.event.inputs.stage }}/lambda-backend.zip" \
            --body "${{ vars.BACKEND_DIR }}/lambda-backend.zip" \
            --output json)
          VERSION_ID=$(echo "$OUTPUT" | jq -r '.VersionId')
          echo "version_id=$VERSION_ID" >> $GITHUB_OUTPUT


      - name: CDK Deploy Backend
        working-directory: ./${{ vars.CDK_DIR }}
        run: |
          npm ci && npx cdk deploy --app "npx ts-node --prefer-ts-exts bin/backend.ts" \
          --require-approval never \
          --context stage=${{ github.event.inputs.stage }} \
          --context appname=${{ github.event.inputs.appname }} \
          --context codeVersionId=${{ steps.upload.outputs.version_id || 'unknown'}}