name: Deploy Frontend

on:
  push:
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend.yml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Skip deploy
        run: |
          echo "Skipping deployment..."
          exit 0
      - uses: actions/checkout@v4

      - name: Build Frontend
        working-directory: frontend
        run: npm ci && npm run build

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::<ACCOUNT_ID>:role/GitHubOIDCRole
          aws-region: ap-northeast-1
          role-session-name: GitHubActions

      - name: Upload to S3
        run: aws s3 sync frontend/dist s3://<YOUR_FRONTEND_BUCKET_NAME> --delete

      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id <YOUR_CF_DIST_ID> \
            --paths "/*"
