name: Deploy Backend Stack

on:
  push:
    paths:
      - 'infrastructure/stacks/backend-stack.ts'
      - '.github/workflows/backend.yml'

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Skip deploy
        run: |
          echo "Skipping deployment..."
          exit 0

      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::<ACCOUNT_ID>:role/GitHubOIDCRole
          aws-region: ap-northeast-1
          role-session-name: GitHubActions

      - name: CDK Deploy Backend
        run: cdk deploy BackendStack-dev --require-approval never